# yaml-language-server: https://squidfunk.github.io/mkdocs-material

# Project information
site_name: My Dev Notes
site_url: https://notes.ozguryazilimci.com
site_author: Özgür Yazılımcı
site_description: >-
  Personal development notes on various topics including Shell, Git, Docker, Kubernetes, Terraform, Java, Node.js, Databases, Networking, Cloud, Mobile Development, Slack, and more.

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    #    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Additional configuration
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ozgurryazilimci
      name: GitHub
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/ozguryazilimci
      name: Docker Hub
    - icon: material/copyright
      link: https://squidfunk.github.io/mkdocs-material/
      name: Mkdocs Material

# Page tree
nav:
  - Home: index.md
  - Shell:
      - Shell Commands: shell/shell-commands.md
      - Bash Completion: shell/bash-completion.md
  - Git:
      - Git Cheatsheet: git/git-cheatsheet.md
      - GitHub Actions: git/github-actions.md
      - Tmate: git/tmate.md
      - List GitHub Actions: git/list-github-actions.md
      - GitHub Pages Custom Domain: git/github-pages-custom-domain.md
      - GitHub Multiple Account: git/github-multiple-accounts.md
      - GitHub Commit Hash Copy: git/github-commit-hash-copy.md
  - Database:
      - MySQL:
          - MySQL Cheatsheet: database/mysql/mysql-cheatsheet.md
          - MySQL Pid File Error: database/mysql/mysql-pid-file-error.md
      - PostgreSQL:
          - PostgreSQL Cheatsheet: database/postgresql/postgresql-cheatsheet.md
          - PostgreSQL JSONB Operations: database/postgresql/postgresql-jsonb-operations.md
      - Tools:
          - Sequel Ace: database/tools/sequel-ace.md
  - Backend:
      - Maven:
          - Maven Wrapper: backend/maven/maven-wrapper.md
      - Java:
          - Jenv: backend/java/jenv.md
          - Sdkman: backend/java/sdkman.md
          - Coding Standards:
              - Checkstyle:
                  - Checkstyle Introduction: backend/java/coding-standards/checkstyle/checkstyle-introduction.md
                  - Maven Checkstyle Plugin: backend/java/coding-standards/checkstyle/maven-checkstyle-plugin.md
                  - Editor Support IntelliJ Idea Checkstyle Plugin: backend/java/coding-standards/checkstyle/editor-support-intellij-idea-checkstyle-plugin.md
              - Codestyle:
                  - Codestyle Introduction: backend/java/coding-standards/codestyle/codestyle-introduction.md
                  - Codestyle IntelliJ IDEA Installation: backend/java/coding-standards/codestyle/codestyle-intellij-idea-installation.md
  - Frontend:
      - Node.js:
          - Nvm & Npm: frontend/nodejs/nvm-npm.md
          - Yarn: frontend/nodejs/yarn.md
          - Npm To Yarn Cheatsheet: frontend/nodejs/npm-to-yarn-cheatsheet.md
  - Mobile:
      - Android:
          - Android Firebase Integration: mobile/android/android-firebase-integration.md
          - Android Keystore Settings: mobile/android/android-keystore-settings.md
          - Android Google Maps Integration: mobile/android/android-google-maps-integration.md
          - Android Push Notification Integration: mobile/android/android-push-notification-integration.md
      - iOS:
          - iOS Firebase Integration: mobile/ios/ios-firebase-integration.md
          - iOS Google Maps Integration: mobile/ios/ios-google-maps-integration.md
          - iOS Test Flight Integration: mobile/ios/ios-test-flight-integration.md
          - iOS Push Notification Integration: mobile/ios/ios-push-notification-integration.md
      - React Native:
          - React Native Basics: mobile/react-native/react-native-basics.md
          - React Native With Typescript: mobile/react-native/react-native-with-typescript.md
          - React Native Utilities: mobile/react-native/react-native-utilities.md
          - React Native Form Handling: mobile/react-native/react-native-form-handling.md
          - React Native Feature Based Architecture: mobile/react-native/react-native-feature-based-architecture.md
          - Expo:
              - Expo Project Setup: mobile/react-native/expo/expo-project-setup.md
              - Expo Router: mobile/react-native/expo/expo-router.md
          - Tailwind CSS: mobile/react-native/tailwind-css.md
          - Nativewind: mobile/react-native/nativewind.md
          - Supabase:
              - Supabase Dashboard Integration: mobile/react-native/supabase/supabase-dashboard-integration.md
              - Supabase CLI Integration: mobile/react-native/supabase/supabase-cli-integration.md
              - Supabase CLI Database Setup: mobile/react-native/supabase/supabase-cli-database-setup.md
              - Supabase CLI RLS Policy: mobile/react-native/supabase/supabase-cli-rls-policies.md
          - TanStack:
              - TanStack Query: mobile/react-native/tanstack/tanstack-query.md
              - Managing Query Keys In TanStack Query: mobile/react-native/tanstack/managing-query-keys-in-tanstack-query.md
              - Testing & Debugging In TanStack Query: mobile/react-native/tanstack/testing-debugging-in-tanstack-query.md
          - UX Pilot: mobile/react-native/ux-pilot.md
          - shadcn/ui: mobile/react-native/shadcn-ui.md
  - Devops:
      - Docker:
          - Docker Introduction: devops/docker/docker-introduction.md
          - Docker Installation: devops/docker/docker-installation.md
          - Docker Cheatsheet: devops/docker/docker-cheatsheet.md
          - Docker Examples: devops/docker/docker-examples.md
          - Docker Useful Scripts: devops/docker/docker-useful-scripts.md
          - Dockerfile: devops/docker/dockerfile.md
          - Docker Compose: devops/docker/docker-compose.md
          - Docker Swarm: devops/docker/docker-swarm.md
      - Kubernetes:
          - Kubernetes Introduction: devops/kubernetes/kubernetes-introduction.md
          - Kubernetes Installation: devops/kubernetes/kubernetes-installation.md
          - Kubernetes Presentation: devops/kubernetes/kubernetes-presentation.md
          - Kubernetes Objects:
              - Pod: devops/kubernetes/kubernetes-objects/pod.md
              - Namespace: devops/kubernetes/kubernetes-objects/namespace.md
              - Label, Selector, Annotation: devops/kubernetes/kubernetes-objects/label-selector-annotation.md
              - Deployment, ReplicaSet: devops/kubernetes/kubernetes-objects/deployment-replicaset.md
              - Rollout, Rollback: devops/kubernetes/kubernetes-objects/rollout-rollback.md
              - StatefulSet: devops/kubernetes/kubernetes-objects/statefulset.md
              - DaemonSet: devops/kubernetes/kubernetes-objects/daemonset.md
              - Job, CronJob: devops/kubernetes/kubernetes-objects/job-cronjob.md
              - Network Structure, Service: devops/kubernetes/kubernetes-objects/network-structure-service.md
              - Ingress: devops/kubernetes/kubernetes-objects/ingress.md
              - Network Policy: devops/kubernetes/kubernetes-objects/network-policy.md
              - ConfigMap: devops/kubernetes/kubernetes-objects/volume-secret-configmap.md
              - Secret, Image Secret: devops/kubernetes/kubernetes-objects/image-secret.md
              - Probes, Resource Limits, Environment Variables: devops/kubernetes/kubernetes-objects/probes-resource-limits-env-variables.md
              - Affinity, Taint, Toleration: devops/kubernetes/kubernetes-objects/affinity-taint-toleration.md
              - Persistent Volume Claim: devops/kubernetes/kubernetes-objects/persistent-volume-claim.md
              - Storage Class: devops/kubernetes/kubernetes-objects/storage-class.md
              - Authentication: devops/kubernetes/kubernetes-objects/authentication.md
              - RBAC: devops/kubernetes/kubernetes-objects/rbac.md
              - Service Account: devops/kubernetes/kubernetes-objects/service-account.md
          - Kubernetes Tools:
              - Kubectl: devops/kubernetes/kubernetes-tools/kubectl.md
              - Kubeadm: devops/kubernetes/kubernetes-tools/kubeadm.md
              - Minikube: devops/kubernetes/kubernetes-tools/minikube.md
              - Dashboards: devops/kubernetes/kubernetes-tools/dashboards.md
              - Helm: devops/kubernetes/kubernetes-tools/helm.md
              - Monitoring (Prometheus, EFK Stack): devops/kubernetes/kubernetes-tools/monitoring-prometheus-efk-stack.md
              - Service Mesh: devops/kubernetes/kubernetes-tools/service-mesh.md
      - Cloud:
          - AWS:
              - AWS Introduction: devops/cloud/aws/aws-introduction.md
              - AWS CLI: devops/cloud/aws/aws-cli.md
              - AWS Services Overview: devops/cloud/aws/aws-services-overview.md
              - AWS Services:
                  - Billing & Cost Management: devops/cloud/aws/aws-services/aws-billing-and-cost-management.md
                  - IAM: devops/cloud/aws/aws-services/aws-iam.md
                  - IAM Demo: devops/cloud/aws/aws-services/aws-iam-demo.md
                  - S3: devops/cloud/aws/aws-services/aws-s3.md
                  - Glacier: devops/cloud/aws/aws-services/aws-glacier.md
                  - EC2: devops/cloud/aws/aws-services/aws-ec2.md
                  - EFS: devops/cloud/aws/aws-services/aws-efs.md
                  - VPC: devops/cloud/aws/aws-services/aws-vpc.md
                  - CloudFront: devops/cloud/aws/aws-services/aws-cloudfront.md
                  - Route53: devops/cloud/aws/aws-services/aws-route53.md
                  - RDS: devops/cloud/aws/aws-services/aws-rds.md
                  - Redshift: devops/cloud/aws/aws-services/aws-redshift.md
                  - DynamoDB: devops/cloud/aws/aws-services/aws-dynamodb.md
                  - ElastiCache: devops/cloud/aws/aws-services/aws-elasticache.md
                  - CloudWatch: devops/cloud/aws/aws-services/aws-cloudwatch.md
                  - CloudTrial: devops/cloud/aws/aws-services/aws-cloudtrial.md
                  - CloudFormation: devops/cloud/aws/aws-services/aws-cloudformation.md
                  - SNS: devops/cloud/aws/aws-services/aws-sns.md
                  - SQS: devops/cloud/aws/aws-services/aws-sqs.md
                  - SWF: devops/cloud/aws/aws-services/aws-swf.md
                  - SES: devops/cloud/aws/aws-services/aws-ses.md
                  - Kinesis: devops/cloud/aws/aws-services/aws-kinesis.md
                  - Config: devops/cloud/aws/aws-services/aws-config.md
                  - OpsWorks: devops/cloud/aws/aws-services/aws-opsworks.md
                  - Lambda & API Gateway: devops/cloud/aws/aws-services/aws-lambda-and-api-gateway.md
                  - Container Services: devops/cloud/aws/aws-services/aws-container-services.md
                  - KMS: devops/cloud/aws/aws-services/aws-kms.md
                  - Directory Service: devops/cloud/aws/aws-services/aws-directory-service.md
                  - Snowball: devops/cloud/aws/aws-services/aws-snowball.md
                  - Storage Gateway: devops/cloud/aws/aws-services/aws-storage-gateway.md
                  - Organizations: devops/cloud/aws/aws-services/aws-organizations.md
                  - Athena Examples: devops/cloud/aws/aws-services/aws-athena-examples.md
      - Terraform:
          - Terraform Cheatsheet: devops/terraform/terraform-cheatsheet.md
          - Tfenv: devops/terraform/tfenv.md
  - Data:
      - Data Tools: data/data-tools.md
  - Network:
      - IP Addresses, IP Ranges, CIDR: network/ip-addresses-ip-ranges-cidr.md
      - DNS & Nameservers: network/dns-nameservers.md
      - DNS Records: network/dns-records.md
      - Domain & Hosting Lookup: network/domain-hosting-lookup.md
      - Shell Network Commands: network/shell-network-commands.md
      - Overriding Hostnames: network/overriding-hostnames.md
      - Internet Speed & IP: network/internet-speed-ip.md
  - Freelance:
      - Freelance Guide: freelance/freelance-guide.md
      - Website:
          - Website Setup: freelance/website/website-setup.md
          - SSL Setup In cPanel: freelance/website/ssl-setup-cpanel.md
          - Mail Server Setup In cPanel: freelance/website/mail-server-setup-cpanel.md
          - WordPress:
              - WordPress Installation: freelance/website/wordpress/wordpress-installation.md
              - WordPress Studio: freelance/website/wordpress/wordpress-studio.md
              - WordPress Admin Dashboard: freelance/website/wordpress/wordpress-admin-dashboard.md
              - WordPress Theme Installation: freelance/website/wordpress/wordpress-theme-installation.md
              - WordPress Theme Customization: freelance/website/wordpress/wordpress-theme-customization.md
              - WordPress Monetization: freelance/website/wordpress/wordpress-monetization.md
              - Themes:
                  - Astra Theme: freelance/website/wordpress/themes/astra-theme.md
                  - Cenote Theme: freelance/website/wordpress/themes/cenote-theme.md
                  - Tyche Theme: freelance/website/wordpress/themes/tyche-theme.md
                  - Storefront Theme: freelance/website/wordpress/themes/storefront-theme.md
              - Plugins:
                  - Really Simple Security Plugin: freelance/website/wordpress/plugins/really-simple-security-plugin.md
                  - Join.chat Plugin: freelance/website/wordpress/plugins/joinchat-plugin.md
                  - Loco Translate Plugin: freelance/website/wordpress/plugins/loco-translate-plugin.md
                  - WooCommerce Plugin: freelance/website/wordpress/plugins/woocommerce-plugin.md
  - Tools:
      - Editor:
          - IntelliJ IDEA: tools/editor/intellij.md
          - Visual Studio Code: tools/editor/vscode.md
      - Slack:
          - Slack Reminder: tools/slack/slack-reminder.md
          - Slack Message: tools/slack/slack-message.md
          - Slack User Group Creation: tools/slack/slack-user-group-creation.md
          - Slack GitHub Workflows: tools/slack/slack-github-workflows.md
      - Chrome Extensions: tools/chrome-extensions.md
      - Apicurio via Docker: tools/apicurio-via-docker.md
      - KafkaUI via Docker: tools/kafkaui-via-docker.md
      - Multi-Gitter: tools/multi-gitter.md
      - Multipass: tools/multipass.md
      - BloomRPC: tools/bloomrpc.md
      - Windows on Mac via UTM: tools/windows-on-mac-via-utm.md
      - Android File Transfer: tools/android-file-transfer.md
      - Useful Resources & Tools: tools/useful-resources-tools.md
  - Other:
      - Modem Admin & Wi-Fi Passwords: other/modem-admin-wifi-passwords.md
      - Recommended Reading List: other/recommended-reading-list.md